collections_dir: docs

collections:
  getting-started:
      output: true
  guides:
     output: true
  references:
     output: true
  components:
     output: true
  releases:
     output: true

algolia:
  application_id: 'OIJ2XNEVHZ'
  index_name:     'test_elasticio_documentation'
  search_only_api_key: 'e434b9595ab515ca31a23e22aa39ecf1'